name: Simple Test

on:
  push:
    branches:
      - main

jobs:
  echo-message:
    runs-on: ubuntu-latest
    env:
      SAMPLE_SECRET: ${{ secrets.SAMPLE_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud (Master Repository Project)'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.MASTER_REPOSITORY_CREDENTIALS }}'
          create_credentials_file: true

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: uriurigit/sample
          path: sample

      - name: Install dependencies And Build
        run: |
          cd sample
          npm install
          npm run build

      - name: Run application
        run: |
          cd sample
          npm start

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-check-sql-file
          path: sample/check-sql/**